<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>AWS on Blog - uTIcARdI</title><link>https://blog.gainskills.top/tags/aws/</link><description>Recent content in AWS on Blog - uTIcARdI</description><generator>Hugo -- gohugo.io</generator><language>en-us</language><lastBuildDate>Thu, 27 Dec 2018 00:00:00 +0000</lastBuildDate><atom:link href="https://blog.gainskills.top/tags/aws/index.xml" rel="self" type="application/rss+xml"/><item><title>AWS S3 Bucket Creation</title><link>https://blog.gainskills.top/2018/12/27/aws-s3-bucket-creation/</link><pubDate>Thu, 27 Dec 2018 00:00:00 +0000</pubDate><guid>https://blog.gainskills.top/2018/12/27/aws-s3-bucket-creation/</guid><description>Try to create a bucket with the Python library: boto3
from boto3.session import Session session=Session(aws_access_key_id=&amp;#39;key1&amp;#39;, aws_secret_access_key=&amp;#39;key2&amp;#39;) s3 = session.resource(&amp;#39;s3&amp;#39;) s3.create_bucket(Bucket=&amp;#39;kz-testbucket&amp;#39;) but failed to run the script with errors:
botocore.exceptions.ClientError: An error occurred (IllegalLocationConstraintException) when calling the CreateBucket operation: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.
botocore.errorfactory.BucketAlreadyExists: An error occurred (BucketAlreadyExists) when calling the CreateBucket operation: The requested bucket name is not available.</description></item></channel></rss>